version: '3.8'
networks:
    trialnetwork:
        driver: bridge
        name: trialnetwork
services:
    mysql2:
        image: mysql:latest
        container_name: mysql2
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        ports:
            - 3306:3306
        expose:
            - 3306
        networks:
            - trialnetwork

    tomcat1:
        image: tomcat:latest
        container_name: tomcat1
        ports:
            - 8787:8080
        expose:
            - 8787
        networks:
            - trialnetwork