version: '3.8'
networks:
    localtryprojekt:
        driver: bridge
        name: localtryprojekt
services:
    mysql2:
        image: mysql:latest
        container_name: mysql2
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=db_blog
            - MYSQL_USER=root
        ports:
            - 3306:3306
        expose:
            - 3306
        networks:
            - localtryprojekt
    tomcat1:
        image: tomcat:latest
        container_name: tomcat1
        environment:
            - TOMCAT_USERNAME=admin
            - TOMCAT_PASSWORD=admin
        ports:
            - 8787:8080
        expose:
            - 8787
        networks:
            - localtryprojekt